### ISSUE TITLE
Compilation failed when upgraded to 2.0.8

### ISSUE THREAD

**Issue by adpande** [jaliss/securesocial#135]
Hi Jaliss,

I am using Play 2.0.4. When I upgraded from SS 2.0.7 to 2.0.8 the application build failed with following error:

sbt.PlayExceptions$CompilationException: Compilation error [cannot find symbol [symbol: class SocialUser] [location: package securesocial.core.java]]
    at sbt.PlayReloader$$anon$2$$anonfun$reload$3$$anonfun$4$$anonfun$apply$12$$anonfun$apply$13.apply(PlayReloader.scala:236) ~[na:na]
    at sbt.PlayReloader$$anon$2$$anonfun$reload$3$$anonfun$4$$anonfun$apply$12$$anonfun$apply$13.apply(PlayReloader.scala:236) ~[na:na]
    at scala.Option.map(Option.scala:133) ~[scala-library.jar:0.11.3]
    at sbt.PlayReloader$$anon$2$$anonfun$reload$3$$anonfun$4$$anonfun$apply$12.apply(PlayReloader.scala:236) ~[na:na]
    at sbt.PlayReloader$$anon$2$$anonfun$reload$3$$anonfun$4$$anonfun$apply$12.apply(PlayReloader.scala:233) ~[na:na]
    at scala.Option.map(Option.scala:133) ~[scala-library.jar:0.11.3]

Is anything changed? Or do I need to configure something to make it work.

Thanks a lot for the wonderful plugin.

Regards,
Abhishek
