### ISSUE TITLE
CustomTemplate & ambigous implicit values

### ISSUE THREAD

**Issue by ZoRdAK** [jaliss/securesocial#197]
Hi,

I installed and configure successfully securesocial (java) for my play 2.0.4 app.
As I wanted to migrate to play 2.1 I decided to migrate securesocial using "master-SNAPSHOT".

```
"securesocial" %% "securesocial" % "master-SNAPSHOT"
```

I'm just running into a problem with my CustomTemplates (impl. written in scala, not Java).

Here is my error log when i'm compiling

```
[info] Compiling 21 Scala sources and 13 Java sources to F:\dev\play2\mycoolapp\target\scala-2.10\classes...
[error] F:\dev\play2\mycoolapp\app\views\securite\Registration\resetPasswordPage.scala.html:17: ambiguous implicit values
:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]     <form action="@securesocial.core.providers.utils.RoutesHelper.handleResetPassword(token).absoluteURL(Identit
yProvider.sslEnabled)"
[error]                                                                                                         ^
[error] F:\dev\play2\mycoolapp\app\views\securite\Registration\signUp.scala.html:19: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]     <form action="@securesocial.core.providers.utils.RoutesHelper.handleSignUp(token).absoluteURL(IdentityProvid
er.sslEnabled)"
[error]                                                                                                  ^
[error] F:\dev\play2\mycoolapp\app\views\securite\Registration\startResetPassword.scala.html:18: ambiguous implicit value
s:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]     <form action="@securesocial.core.providers.utils.RoutesHelper.handleStartResetPassword().absoluteURL(Identit
yProvider.sslEnabled)"
[error]                                                                                                         ^
[error] F:\dev\play2\mycoolapp\app\views\securite\Registration\startSignUp.scala.html:18: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]     <form action="@securesocial.core.providers.utils.RoutesHelper.handleStartSignUp().absoluteURL(IdentityProvid
er.sslEnabled)"
[error]                                                                                                  ^
[error] F:\dev\play2\mycoolapp\app\views\securite\login.scala.html:47: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]                                 @provider(p.id)
[error]                                          ^
[error] F:\dev\play2\mycoolapp\app\views\securite\mails\alreadyRegisteredEmail.scala.html:9: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]             <a href="@securesocial.core.providers.utils.RoutesHelper.startResetPassword().absoluteURL(IdentityPr
ovider.sslEnabled)">here</a> to reset it.</p>
[error]                                                                                                      ^
[error] F:\dev\play2\mycoolapp\app\views\securite\mails\passwordChangedNotice.scala.html:9: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]     <a href="@securesocial.core.providers.utils.RoutesHelper.login.absoluteURL(IdentityProvider.sslEnabled)">her
e</a></p>
[error]                                                                               ^
[error] F:\dev\play2\mycoolapp\app\views\securite\mails\passwordResetEmail.scala.html:8: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]     <a href="@securesocial.core.providers.utils.RoutesHelper.resetPassword(token).absoluteURL(IdentityProvider.s
slEnabled)">
[error]                                                                                              ^
[error] F:\dev\play2\mycoolapp\app\views\securite\mails\signUpEmail.scala.html:8: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]     <a href="@securesocial.core.providers.utils.RoutesHelper.signUp(token).absoluteURL(IdentityProvider.sslEnabl
ed)">link</a> to complete your registration.
[error]                                                                                       ^
[error] F:\dev\play2\mycoolapp\app\views\securite\mails\welcomeEmail.scala.html:9: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]     Click <a href="@securesocial.core.providers.utils.RoutesHelper.login.absoluteURL(IdentityProvider.sslEnabled
)">here</a> to log in</p>
[error]                                                                                     ^
[error] F:\dev\play2\mycoolapp\app\views\securite\passwordChange.scala.html:24: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]             <a class="btn" href="@securesocial.controllers.ProviderController.toUrl">@Messages("securesocial.pas
swordChange.okButton")</a>
[error]                                                                               ^
[error] F:\dev\play2\mycoolapp\app\views\securite\provider.scala.html:20: ambiguous implicit values:
[error]  both method requestHeader in object PlayMagicForJava of type => play.api.mvc.RequestHeader
[error]  and value request of type play.api.mvc.RequestHeader
[error]  match expected type play.api.mvc.RequestHeader
[error]                 <form action = "@securesocial.core.providers.utils.RoutesHelper.authenticateByPost("userpass").a
bsoluteURL(IdentityProvider.sslEnabled)"
[error]
          ^
[error] 12 errors found
[error] (compile:compile) Compilation failed
[error] Total time: 17 s, completed 12 avr. 2013 00:00:12
```

All my "custom" views are simply duplicates of the securesocial module-core ones with some "java particularity" like :

@(resetForm:play.data.Form[(String, String)], token: String)(implicit request: play.api.mvc.RequestHeader)

instead of 

@(resetForm:Form[(String, String)], token: String)(implicit request: RequestHeader)

But it worked in 2.0.4
