### ISSUE TITLE
Errors when upgrading from 2.1.4 to 3.0-M3

### ISSUE THREAD

**Issue by mullex** [jaliss/securesocial#537]
I met the following errors and couldn't find any documentation how to fix these e.g. what type parameter should i put for SecureSocial etc. Could anyone help please?

[error] /Work/Project/Application.scala:10:: trait SecureSocial takes type parameters
[error] object ApplicationHandler extends Controller with SecureSocial {

[error] /Work/Project/Application.scala:64: type Identity is not a member of package securesocial.core
[error]   def getUser(implicit request: play.api.mvc.Request[Any]): Option[securesocial.core.Identity] = {

[error] /Work/Project/Application.scala:42: type SecuredRequest is not a member of package securesocial.core
[error]       case r: securesocial.core.SecuredRequest[_] => Some(r.user)
