### ISSUE TITLE
Execution exception in 2.0.6

### ISSUE THREAD

**Issue by pvillega** [jaliss/securesocial#269]
Hi,

I moved an app from 2.0.4 to 2.0.6 and suddenly I get:

```
 [NoClassDefFoundError: Could not initialize class securesocial.core.providers.utils.RoutesHelper$] 
```

when trying to access `/login` 

It works fine in 2.0.4 so it seems an issue between SecureSocial and 2.0.6... any  idea?
